using System.Security.Cryptography;using System.Text;using RutaCero.Application.Accounts;using RutaCero.Application.Common;using RutaCero.Application.Transactions;using RutaCero.Domain.Imports;using RutaCero.Domain.ValueObjects;using RutaCero.Domain.Transactions;
namespace RutaCero.Application.Imports;
public sealed class StatementImportService(IStatementImportRepository imports,IFinancialAccountRepository accounts,ITransactionRepository transactions,ICategorizationRuleRepository rules,IPrivateFileStorage storage,IEnumerable<IStatementParser> parsers,IUnitOfWork unitOfWork)
{
 public async Task<Result<StatementImportDto>> UploadAsync(Guid userId,Guid accountId,string fileName,string contentType,long size,Stream content,CancellationToken token)
 {
  if(size is<=0 or>20_000_000)return Result<StatementImportDto>.Failure("El archivo excede el tamaño permitido.");
  if(await accounts.FindAsync(accountId,userId,token)is null)return Result<StatementImportDto>.Failure("La cuenta no existe.");
  await using var memory=new MemoryStream();await content.CopyToAsync(memory,token);var hash=new ImportHash(Convert.ToHexString(SHA256.HashData(memory.ToArray())));
  if(await imports.ExistsAsync(userId,hash,token))return Result<StatementImportDto>.Failure("Este estado de cuenta ya fue importado.");
  var extension=Path.GetExtension(fileName).ToLowerInvariant();var parser=parsers.FirstOrDefault(x=>x.CanParse(contentType,extension));if(parser is null)return Result<StatementImportDto>.Failure("El formato del archivo no es compatible.");
  var stored=$"{Guid.NewGuid():N}{extension}";memory.Position=0;var key=await storage.SaveAsync(userId,stored,memory,token);
  var item=new StatementImport(userId,accountId,Path.GetFileName(fileName),stored,contentType,size,hash,key,DateTimeOffset.UtcNow);memory.Position=0;
  var rows=await parser.ParseAsync(memory,token);if(extension==".pdf"&&rows.Count==0)item.MarkRequiresOcr();else item.MarkPendingReview(rows.Count);
  await imports.AddAsync(item,token);var account=(await accounts.FindAsync(accountId,userId,token))!;var userRules=await rules.ListAsync(userId,token);var seen=new HashSet<string>();var categorizer=new CategorizationService();var drafts=new List<StatementImportRow>();foreach(var row in rows){var fingerprint=Fingerprint(accountId,row);var duplicate=!seen.Add(fingerprint)||await imports.FingerprintExistsAsync(userId,fingerprint,token);var money=new Money(row.Amount,account.CurrentBalance.Currency);var type=row.IsCredit?TransactionType.Income:TransactionType.Expense;var draft=new StatementImportRow(userId,item.Id,fingerprint,row.Date,row.Description,money,row.IsCredit,duplicate);draft.Suggest(categorizer.Categorize(userRules,row.Description,account.InstitutionName,accountId,money,type),type);drafts.Add(draft);}await imports.AddRowsAsync(drafts,token);await unitOfWork.SaveChangesAsync(token);return Result<StatementImportDto>.Success(Map(item));
 }
 public async Task<IReadOnlyList<StatementImportDto>> ListAsync(Guid userId,CancellationToken token)=>(await imports.ListAsync(userId,token)).Select(Map).ToList();
 public async Task<IReadOnlyList<ImportRowDto>> RowsAsync(Guid userId,Guid importId,CancellationToken token)=>(await imports.ListRowsAsync(importId,userId,token)).Select(MapRow).ToList();
 public async Task<Result<int>> ConfirmAsync(Guid userId,Guid importId,ConfirmImportCommand command,CancellationToken token){var import=await imports.FindAsync(importId,userId,token);if(import is null)return Result<int>.Failure("La importación no existe.");var account=await accounts.FindAsync(import.FinancialAccountId,userId,token);if(account is null)return Result<int>.Failure("La cuenta no existe.");var rows=await imports.ListRowsAsync(importId,userId,token);var choices=command.Rows.ToDictionary(x=>x.Id);var accepted=0;foreach(var row in rows.Where(x=>choices.ContainsKey(x.Id))){var choice=choices[row.Id];if(!choice.Accept){row.Reject();continue;}row.Accept(choice.CategoryId,choice.TransactionType);await transactions.AddAsync(new Transaction(userId,account.Id,null,choice.CategoryId,choice.TransactionType,row.Amount,row.Date,row.Description,DateTimeOffset.UtcNow),token);accepted++;}import.Confirm();await unitOfWork.SaveChangesAsync(token);return Result<int>.Success(accepted);}
 private static string Fingerprint(Guid accountId,ParsedStatementRow row)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{accountId:N}|{row.Date:yyyyMMdd}|{row.Description.Trim().ToUpperInvariant()}|{row.Amount:F2}|{row.IsCredit}")));
 private static ImportRowDto MapRow(StatementImportRow x)=>new(x.Id,x.Date,x.Description,x.Amount.Amount,x.Amount.Currency,x.IsCredit,x.Status,x.CategoryId,x.TransactionType);
 private static StatementImportDto Map(StatementImport x)=>new(x.Id,x.FinancialAccountId,x.OriginalFileName,x.ContentType,x.Size,x.Sha256.Value,x.Status,x.ExtractedCount,x.UploadedAt);
}
