import {MoneyFormatPipe} from '../../shared/money-format.pipe';
import {AppHeader} from '../../core/app-header';
import {HttpClient} from '@angular/common/http';import {ChangeDetectionStrategy,Component,inject,signal} from '@angular/core';import {FormControl,FormGroup,ReactiveFormsModule} from '@angular/forms';import {forkJoin} from 'rxjs';import {RouterLink} from '@angular/router';
interface Income{id:string;name:string;amount:number;currency:string;expectedDate:string;frequency:string;isConfirmed:boolean}interface Commitment{id:string;name:string;amount:number;currency:string;frequency:string;nextDueDate:string;isEssential:boolean}interface Settings{safetyReserveAmount:number;safetyReserveMode:string;minimumDaysOfEssentialExpenses:number;defaultRecommendationProfile:string;defaultTimeZone:string;baseCurrency:string;allowEstimatedBalancesInRecommendations:boolean}
@Component({standalone:true,imports:[MoneyFormatPipe,AppHeader,ReactiveFormsModule],templateUrl:'./planning-page.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class PlanningPage{
 private readonly http=inject(HttpClient);readonly incomes=signal<Income[]>([]);readonly commitments=signal<Commitment[]>([]);readonly error=signal('');
 readonly income=new FormGroup({name:new FormControl('',{nonNullable:true}),amount:new FormControl(0,{nonNullable:true}),currency:new FormControl('HNL',{nonNullable:true}),expectedDate:new FormControl(new Date().toISOString().slice(0,10),{nonNullable:true}),frequency:new FormControl('Once',{nonNullable:true}),isConfirmed:new FormControl(false,{nonNullable:true}),destinationFinancialAccountId:new FormControl<string|null>(null)});
 readonly commitment=new FormGroup({name:new FormControl('',{nonNullable:true}),categoryId:new FormControl<string|null>(null),amount:new FormControl(0,{nonNullable:true}),currency:new FormControl('HNL',{nonNullable:true}),frequency:new FormControl('Monthly',{nonNullable:true}),nextDueDate:new FormControl(new Date().toISOString().slice(0,10),{nonNullable:true}),endDate:new FormControl<string|null>(null),isEssential:new FormControl(true,{nonNullable:true}),sourceFinancialAccountId:new FormControl<string|null>(null),debtId:new FormControl<string|null>(null)});
 readonly settings=new FormGroup({safetyReserveAmount:new FormControl(0,{nonNullable:true}),safetyReserveMode:new FormControl('FixedAmount',{nonNullable:true}),minimumDaysOfEssentialExpenses:new FormControl(30,{nonNullable:true}),defaultRecommendationProfile:new FormControl('Balanced',{nonNullable:true}),defaultTimeZone:new FormControl('America/Tegucigalpa',{nonNullable:true}),baseCurrency:new FormControl('HNL',{nonNullable:true}),allowEstimatedBalancesInRecommendations:new FormControl(false,{nonNullable:true})});
 constructor(){forkJoin({i:this.http.get<Income[]>('/api/v1/expected-incomes'),c:this.http.get<Commitment[]>('/api/v1/recurring-commitments'),s:this.http.get<Settings>('/api/v1/settings')}).subscribe({next:x=>{this.incomes.set(x.i);this.commitments.set(x.c);this.settings.setValue(x.s);},error:()=>this.error.set('No fue posible cargar la planeación.')});}
 addIncome(){this.http.post<Income>('/api/v1/expected-incomes',this.income.getRawValue()).subscribe(x=>this.incomes.update(v=>[...v,x]));}addCommitment(){this.http.post<Commitment>('/api/v1/recurring-commitments',this.commitment.getRawValue()).subscribe(x=>this.commitments.update(v=>[...v,x]));}saveSettings(){this.http.put<Settings>('/api/v1/settings',this.settings.getRawValue()).subscribe();}
}



