import {MoneyFormatPipe} from '../../shared/money-format.pipe';
import {AppHeader} from '../../core/app-header';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectionStrategy,Component,inject,signal } from '@angular/core';
import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';

interface Account{id:string;displayName:string;currency:string} interface Category{id:string;name:string}
interface Debt{id:string;name:string;institutionName:string;currentPrincipal:number;currency:string;status:string}
interface Movement{id:string;financialAccountId:string;relatedFinancialAccountId:string|null;categoryId:string|null;type:string;amount:number;currency:string;transactionDate:string;description:string;transferGroupId:string|null;transferDirection:'Outgoing'|'Incoming'|null;debtId:string|null}
interface TypeSetting{code:string;label:string;effect:'Positive'|'Negative'|'Neutral'}
@Component({standalone:true,imports:[MoneyFormatPipe,AppHeader,ReactiveFormsModule,FormsModule],templateUrl:'./transactions-page.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class TransactionsPage{
 private readonly http=inject(HttpClient);readonly movements=signal<Movement[]>([]);readonly accounts=signal<Account[]>([]);readonly debts=signal<Debt[]>([]);readonly categories=signal<Category[]>([]);readonly typeSettings=signal<TypeSetting[]>([]);readonly showForm=signal(false);readonly showTypeSettings=signal(false);readonly editing=signal<Movement|null>(null);readonly deleting=signal<Movement|null>(null);readonly error=signal('');readonly notice=signal('');readonly modalError=signal('');
 readonly form=new FormGroup({financialAccountId:new FormControl('',{nonNullable:true,validators:Validators.required}),relatedFinancialAccountId:new FormControl<string|null>(null),relatedAmount:new FormControl<number|null>(null),relatedCurrency:new FormControl<string|null>(null),debtId:new FormControl<string|null>(null),principalAmount:new FormControl<number|null>(null),isAllocationConfirmed:new FormControl(false,{nonNullable:true}),categoryId:new FormControl<string|null>(null),type:new FormControl('Expense',{nonNullable:true}),amount:new FormControl(0,{nonNullable:true,validators:Validators.min(.01)}),currency:new FormControl('HNL',{nonNullable:true,validators:Validators.required}),transactionDate:new FormControl(new Date().toISOString().slice(0,10),{nonNullable:true}),description:new FormControl('',{nonNullable:true,validators:Validators.required})});
 readonly editForm=new FormGroup({financialAccountId:new FormControl('',{nonNullable:true,validators:Validators.required}),relatedFinancialAccountId:new FormControl<string|null>(null),debtId:new FormControl<string|null>(null),principalAmount:new FormControl<number|null>(null),isAllocationConfirmed:new FormControl(false,{nonNullable:true}),categoryId:new FormControl<string|null>(null),type:new FormControl('Expense',{nonNullable:true}),amount:new FormControl(0,{nonNullable:true,validators:Validators.min(.01)}),currency:new FormControl('HNL',{nonNullable:true,validators:Validators.required}),transactionDate:new FormControl('',{nonNullable:true}),description:new FormControl('',{nonNullable:true,validators:Validators.required})});
 constructor(){this.load();}
 load(){forkJoin({movements:this.http.get<Movement[]>('/api/v1/transactions'),accounts:this.http.get<Account[]>('/api/v1/accounts'),debts:this.http.get<Debt[]>('/api/v1/debts'),categories:this.http.get<Category[]>('/api/v1/categories'),types:this.http.get<TypeSetting[]>('/api/v1/transaction-types')}).subscribe({next:x=>{this.movements.set(x.movements);this.accounts.set(x.accounts);this.debts.set(x.debts.filter(d=>d.status==='Active'));this.categories.set(x.categories);this.typeSettings.set(x.types);},error:()=>this.error.set('No fue posible cargar los movimientos.')});}
 openForm(){this.form.reset({financialAccountId:'',relatedFinancialAccountId:null,relatedAmount:null,relatedCurrency:null,debtId:null,principalAmount:null,isAllocationConfirmed:false,categoryId:null,type:'Expense',amount:0,currency:'HNL',transactionDate:new Date().toISOString().slice(0,10),description:''});this.modalError.set('');this.showForm.set(true);}
 accountChanged(){const currency=this.accounts().find(x=>x.id===this.form.controls.financialAccountId.value)?.currency;if(currency)this.form.controls.currency.setValue(currency);}
 editAccountChanged(){const currency=this.accounts().find(x=>x.id===this.editForm.controls.financialAccountId.value)?.currency;if(currency)this.editForm.controls.currency.setValue(currency);}
 destinationChanged(){const currency=this.accounts().find(x=>x.id===this.form.controls.relatedFinancialAccountId.value)?.currency;if(currency)this.form.controls.relatedCurrency.setValue(currency);}
 isTransfer(){return this.form.controls.type.value==='Transfer';}
 isDebtPayment(){return this.form.controls.type.value==='DebtPayment';}
 debtChanged(){const debt=this.debts().find(x=>x.id===this.form.controls.debtId.value);if(debt)this.form.controls.currency.setValue(debt.currency);}
 save(){if(this.form.invalid)return;const transfer=this.isTransfer();const debtPayment=this.isDebtPayment();if(transfer&&(!this.form.controls.relatedFinancialAccountId.value||!this.form.controls.relatedAmount.value||!this.form.controls.relatedCurrency.value)){this.modalError.set('Completa la cuenta, monto y moneda de destino.');return;}if(debtPayment&&(!this.form.controls.debtId.value||!this.form.controls.principalAmount.value||!this.form.controls.isAllocationConfirmed.value)){this.modalError.set('Selecciona la deuda y confirma cuánto corresponde a capital.');return;}if(debtPayment&&this.form.controls.principalAmount.value!>this.form.controls.amount.value){this.modalError.set('El capital confirmado no puede superar el monto total.');return;}this.http.post<Movement>('/api/v1/transactions',this.form.getRawValue()).subscribe({next:()=>{this.http.get<Movement[]>('/api/v1/transactions').subscribe(x=>this.movements.set(x));this.showForm.set(false);this.error.set('');this.notice.set(transfer?'Transferencia compensatoria registrada correctamente.':debtPayment?'Pago registrado y saldo de deuda actualizado correctamente.':'Movimiento registrado correctamente.');},error:e=>this.modalError.set(e.error?.title??'No fue posible guardar el movimiento.')});}
 accountName(id:string){return this.accounts().find(x=>x.id===id)?.displayName??'Cuenta';} categoryName(id:string|null){return this.categories().find(x=>x.id===id)?.name??'Sin clasificar';}
 typeLabel(type:string){return this.typeSettings().find(x=>x.code===type)?.label??type;}
 effect(type:string){return this.typeSettings().find(x=>x.code===type)?.effect??'Neutral';}
 sign(type:string,direction:'Outgoing'|'Incoming'|null=null){if(type==='Transfer'&&direction)return direction==='Incoming'?'+':'−';return this.effect(type)==='Positive'?'+':this.effect(type)==='Negative'?'−':'';}
 saveType(setting:TypeSetting){this.http.put<TypeSetting>(`/api/v1/transaction-types/${setting.code}`,{label:setting.label,effect:setting.effect}).subscribe({next:x=>{this.typeSettings.update(v=>v.map(t=>t.code===x.code?x:t));this.notice.set('Tipo de movimiento actualizado correctamente.');},error:()=>this.modalError.set('No fue posible actualizar el tipo.')});}
 edit(item:Movement){this.modalError.set('');this.editForm.reset({financialAccountId:item.financialAccountId,relatedFinancialAccountId:null,debtId:item.debtId,principalAmount:null,isAllocationConfirmed:false,categoryId:item.categoryId,type:item.type,amount:item.amount,currency:item.currency,transactionDate:item.transactionDate,description:item.description});this.editing.set(item);}
 isEditDebtPayment(){return this.editForm.controls.type.value==='DebtPayment';}
 editDebtChanged(){const debt=this.debts().find(x=>x.id===this.editForm.controls.debtId.value);if(debt)this.editForm.controls.currency.setValue(debt.currency);}
 update(){const item=this.editing();if(!item||this.editForm.invalid)return;if(this.isEditDebtPayment()&&(!this.editForm.controls.debtId.value||!this.editForm.controls.principalAmount.value||!this.editForm.controls.isAllocationConfirmed.value)){this.modalError.set('Selecciona la deuda y confirma cuánto corresponde a capital.');return;}if(this.isEditDebtPayment()&&this.editForm.controls.principalAmount.value!>this.editForm.controls.amount.value){this.modalError.set('El capital confirmado no puede superar el monto total.');return;}this.http.put<Movement>(`/api/v1/transactions/${item.id}`,this.editForm.getRawValue()).subscribe({next:x=>{this.movements.update(v=>v.map(m=>m.id===x.id?x:m));this.editing.set(null);this.error.set('');this.notice.set(this.isEditDebtPayment()?'Movimiento vinculado y deuda actualizada correctamente.':'Cambios guardados correctamente.');},error:e=>this.modalError.set(e.error?.title??'No fue posible guardar los cambios.')});}
 remove(){const item=this.deleting();if(!item)return;this.http.delete(`/api/v1/transactions/${item.id}`).subscribe({next:()=>{this.movements.update(v=>v.filter(m=>item.transferGroupId?m.transferGroupId!==item.transferGroupId:m.id!==item.id));this.deleting.set(null);this.error.set('');this.notice.set(item.transferGroupId?'Transferencia y sus dos movimientos eliminados correctamente.':'Movimiento eliminado correctamente.');},error:()=>this.modalError.set('No fue posible eliminar el movimiento.')});}
}



