using RutaCero.Domain.Planning;
using RutaCero.Domain.ValueObjects;
namespace RutaCero.Application.Planning;
public sealed class PlanningService(IPlanningRepository repository,IUnitOfWork unitOfWork)
{
 public async Task<IReadOnlyList<ExpectedIncomeDto>> IncomesAsync(Guid userId,CancellationToken token)=>(await repository.ListIncomesAsync(userId,token)).Select(x=>new ExpectedIncomeDto(x.Id,x.Name,x.Amount.Amount,x.Amount.Currency,x.ExpectedDate,x.Frequency,x.IsConfirmed,x.DestinationFinancialAccountId)).ToList();
 public async Task<ExpectedIncomeDto> AddIncomeAsync(Guid userId,CreateExpectedIncomeCommand c,CancellationToken token){var x=new ExpectedIncome(userId,c.Name,new(c.Amount,c.Currency),c.ExpectedDate,c.Frequency,c.IsConfirmed,c.DestinationFinancialAccountId);await repository.AddIncomeAsync(x,token);await unitOfWork.SaveChangesAsync(token);return new(x.Id,x.Name,x.Amount.Amount,x.Amount.Currency,x.ExpectedDate,x.Frequency,x.IsConfirmed,x.DestinationFinancialAccountId);}
 public async Task<IReadOnlyList<CommitmentDto>> CommitmentsAsync(Guid userId,CancellationToken token)=>(await repository.ListCommitmentsAsync(userId,token)).Select(Map).ToList();
 public async Task<CommitmentDto> AddCommitmentAsync(Guid userId,CreateCommitmentCommand c,CancellationToken token){var x=new RecurringCommitment(userId,c.Name,c.CategoryId,new(c.Amount,c.Currency),c.Frequency,c.NextDueDate,c.EndDate,c.IsEssential,c.SourceFinancialAccountId,c.DebtId);await repository.AddCommitmentAsync(x,token);await unitOfWork.SaveChangesAsync(token);return Map(x);}
 public async Task<IReadOnlyList<BudgetDto>> BudgetsAsync(Guid userId,int year,int month,CancellationToken token)=>(await repository.ListBudgetsAsync(userId,year,month,token)).Select(x=>new BudgetDto(x.Id,x.CategoryId,x.Year,x.Month,x.Amount.Amount,x.Amount.Currency)).ToList();
 public async Task<BudgetDto> SetBudgetAsync(Guid userId,CreateBudgetCommand c,CancellationToken token){var x=new MonthlyBudget(userId,c.CategoryId,c.Year,c.Month,new(c.Amount,c.Currency));await repository.UpsertBudgetAsync(x,token);await unitOfWork.SaveChangesAsync(token);return new(x.Id,x.CategoryId,x.Year,x.Month,x.Amount.Amount,x.Amount.Currency);}
 public async Task<SettingsDto> SettingsAsync(Guid userId,CancellationToken token){var x=await repository.GetSettingsAsync(userId,token)??new(userId,0,SafetyReserveMode.FixedAmount,30,RecommendationProfile.Balanced,"America/Tegucigalpa",Currency.HNL,false);return Map(x);}
 public async Task<SettingsDto> SaveSettingsAsync(Guid userId,SettingsDto c,CancellationToken token){var x=new UserFinancialSettings(userId,c.SafetyReserveAmount,c.SafetyReserveMode,c.MinimumDaysOfEssentialExpenses,c.DefaultRecommendationProfile,c.DefaultTimeZone,c.BaseCurrency,c.AllowEstimatedBalancesInRecommendations);await repository.UpsertSettingsAsync(x,token);await unitOfWork.SaveChangesAsync(token);return Map(x);}
 private static CommitmentDto Map(RecurringCommitment x)=>new(x.Id,x.Name,x.CategoryId,x.Amount.Amount,x.Amount.Currency,x.Frequency,x.NextDueDate,x.EndDate,x.IsEssential,x.IsActive,x.SourceFinancialAccountId,x.DebtId);
 private static SettingsDto Map(UserFinancialSettings x)=>new(x.SafetyReserveAmount,x.SafetyReserveMode,x.MinimumDaysOfEssentialExpenses,x.DefaultRecommendationProfile,x.DefaultTimeZone,x.BaseCurrency,x.AllowEstimatedBalancesInRecommendations);
}
