import {MoneyFormatPipe} from '../../shared/money-format.pipe';
import {AppHeader} from '../../core/app-header';
import {HttpClient} from '@angular/common/http';import {ChangeDetectionStrategy,Component,inject,signal} from '@angular/core';import {FormsModule} from '@angular/forms';import {forkJoin,of,switchMap} from 'rxjs';
interface Account{id:string;displayName:string}interface Debt{id:string;name:string;institutionName:string;currentPrincipal:number;currency:string;status:string}interface Import{id:string;originalFileName:string;contentType:string;size:number;status:string;extractedCount:number;uploadedAt:string}
interface Row{id:string;date:string;description:string;amount:number;currency:string;isCredit:boolean;status:string;categoryId:string|null;transactionType:string|null;accept?:boolean}
@Component({standalone:true,imports:[MoneyFormatPipe,AppHeader,FormsModule],templateUrl:'./statement-imports-page.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class StatementImportsPage{
 private readonly http=inject(HttpClient);readonly accounts=signal<Account[]>([]);readonly debts=signal<Debt[]>([]);readonly imports=signal<Import[]>([]);readonly rows=signal<Row[]>([]);readonly selected=signal<Import|null>(null);readonly error=signal('');readonly notice=signal('');readonly pending=signal(false);accountId='';file:File|null=null;debtId='';confirmedDebtBalance:number|null=null;statementDate=new Date().toISOString().slice(0,10);
 constructor(){this.load();}load(){forkJoin({accounts:this.http.get<Account[]>('/api/v1/accounts'),debts:this.http.get<Debt[]>('/api/v1/debts'),imports:this.http.get<Import[]>('/api/v1/statement-imports')}).subscribe({next:x=>{this.accounts.set(x.accounts);this.debts.set(x.debts);this.imports.set(x.imports);},error:()=>this.error.set('No fue posible cargar las importaciones.')});}
 choose(event:Event){this.file=(event.target as HTMLInputElement).files?.[0]??null;}
 upload(){if(!this.file||!this.accountId)return;this.pending.set(true);const data=new FormData();data.append('financialAccountId',this.accountId);data.append('file',this.file);this.http.post<Import>('/api/v1/statement-imports',data).subscribe({next:x=>{this.imports.update(v=>[x,...v]);this.pending.set(false);},error:r=>{this.error.set(r.error?.title??'No fue posible importar el archivo.');this.pending.set(false);}});}
 review(item:Import){this.selected.set(item);this.debtId='';this.confirmedDebtBalance=null;this.statementDate=new Date().toISOString().slice(0,10);this.http.get<Row[]>(`/api/v1/statement-imports/${item.id}/rows`).subscribe(x=>this.rows.set(x.map(r=>({...r,accept:r.status!=='Duplicate'}))));}
 confirm(){const item=this.selected();if(!item)return;if(this.debtId&&this.confirmedDebtBalance===null){this.error.set('Ingresa el saldo confirmado que muestra el estado de la deuda.');return;}const rows=this.rows().map(x=>({id:x.id,accept:x.accept??false,categoryId:x.categoryId,transactionType:x.transactionType??(x.isCredit?'Income':'Expense')}));this.pending.set(true);this.http.post<number>(`/api/v1/statement-imports/${item.id}/confirm`,{rows}).pipe(switchMap(()=>this.debtId?this.http.post(`/api/v1/debts/${this.debtId}/balance-confirmations`,{statementImportId:item.id,statementDate:this.statementDate,balance:this.confirmedDebtBalance}):of(null))).subscribe({next:()=>{this.imports.update(v=>v.map(x=>x.id===item.id?{...x,status:'Confirmed'}:x));this.selected.set(null);this.pending.set(false);this.error.set('');this.notice.set(this.debtId?'Estado confirmado y saldo de deuda actualizado.':'Estado importado correctamente.');},error:e=>{this.pending.set(false);this.error.set(e.error?.title??'No fue posible confirmar el estado.');}});}
 label(status:string){return({Uploaded:'Subido',RequiresOcr:'Requiere OCR',PendingReview:'Pendiente de revisión',Confirmed:'Confirmado',Rejected:'Rechazado'}as Record<string,string>)[status]??status;}
}



