import {ChangeDetectionStrategy,Component,inject,signal} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {FormControl,FormGroup,ReactiveFormsModule,Validators} from '@angular/forms';
import {forkJoin} from 'rxjs';
import {AppHeader} from '../../core/app-header';
import {MoneyFormatPipe} from '../../shared/money-format.pipe';

interface Commitment{id:string;name:string;categoryId:string|null;amount:number;currency:string;frequency:string;nextDueDate:string;endDate:string|null;isEssential:boolean;isActive:boolean;sourceFinancialAccountId:string|null;debtId:string|null}
interface Account{id:string;displayName:string;currency:string}interface Category{id:string;name:string}interface Debt{id:string;name:string;currency:string;status:string}

@Component({standalone:true,imports:[AppHeader,ReactiveFormsModule,MoneyFormatPipe],templateUrl:'./recurring-commitments-page.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class RecurringCommitmentsPage{
 private readonly http=inject(HttpClient);readonly items=signal<Commitment[]>([]);readonly accounts=signal<Account[]>([]);readonly categories=signal<Category[]>([]);readonly debts=signal<Debt[]>([]);readonly showForm=signal(false);readonly editing=signal<Commitment|null>(null);readonly deleting=signal<Commitment|null>(null);readonly error=signal('');readonly modalError=signal('');readonly notice=signal('');
 readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:Validators.required}),categoryId:new FormControl<string|null>(null),amount:new FormControl(0,{nonNullable:true,validators:Validators.min(.01)}),currency:new FormControl('HNL',{nonNullable:true}),frequency:new FormControl('Monthly',{nonNullable:true}),nextDueDate:new FormControl(new Date().toISOString().slice(0,10),{nonNullable:true}),endDate:new FormControl<string|null>(null),isEssential:new FormControl(true,{nonNullable:true}),sourceFinancialAccountId:new FormControl<string|null>(null),debtId:new FormControl<string|null>(null)});
 constructor(){forkJoin({items:this.http.get<Commitment[]>('/api/v1/recurring-commitments'),accounts:this.http.get<Account[]>('/api/v1/accounts'),categories:this.http.get<Category[]>('/api/v1/categories'),debts:this.http.get<Debt[]>('/api/v1/debts')}).subscribe({next:x=>{this.items.set(x.items);this.accounts.set(x.accounts);this.categories.set(x.categories);this.debts.set(x.debts.filter(d=>d.status==='Active'));},error:()=>this.error.set('No fue posible cargar los compromisos recurrentes.')});}
 open(){this.editing.set(null);this.modalError.set('');this.form.reset({name:'',categoryId:null,amount:0,currency:'HNL',frequency:'Monthly',nextDueDate:new Date().toISOString().slice(0,10),endDate:null,isEssential:true,sourceFinancialAccountId:null,debtId:null});this.showForm.set(true);}
 edit(x:Commitment){this.editing.set(x);this.modalError.set('');this.form.reset({name:x.name,categoryId:x.categoryId,amount:x.amount,currency:x.currency,frequency:x.frequency,nextDueDate:x.nextDueDate,endDate:x.endDate,isEssential:x.isEssential,sourceFinancialAccountId:x.sourceFinancialAccountId,debtId:x.debtId});this.showForm.set(true);}
 save(){if(this.form.invalid)return;const editing=this.editing();const request=editing?this.http.put<Commitment>(`/api/v1/recurring-commitments/${editing.id}`,this.form.getRawValue()):this.http.post<Commitment>('/api/v1/recurring-commitments',this.form.getRawValue());request.subscribe({next:x=>{this.items.update(v=>editing?v.map(i=>i.id===x.id?x:i):[...v,x]);this.showForm.set(false);this.editing.set(null);this.notice.set(editing?'Compromiso actualizado correctamente.':'Compromiso registrado correctamente.');},error:()=>this.modalError.set('No fue posible guardar el compromiso.')});}
 remove(){const x=this.deleting();if(!x)return;this.http.delete(`/api/v1/recurring-commitments/${x.id}`).subscribe({next:()=>{this.items.update(v=>v.filter(i=>i.id!==x.id));this.deleting.set(null);this.notice.set('Compromiso eliminado correctamente.');},error:()=>this.modalError.set('No fue posible eliminar el compromiso.')});}
 useAccount(){const account=this.accounts().find(x=>x.id===this.form.controls.sourceFinancialAccountId.value);if(account)this.form.controls.currency.setValue(account.currency);}
 categoryName(id:string|null){return this.categories().find(x=>x.id===id)?.name??'Sin categoría';}accountName(id:string|null){return this.accounts().find(x=>x.id===id)?.displayName??'Sin cuenta';}frequencyLabel(x:string){return({Once:'Una vez',Weekly:'Semanal',Biweekly:'Quincenal',Monthly:'Mensual',Quarterly:'Trimestral',Yearly:'Anual'} as Record<string,string>)[x]??x;}
}
