using RutaCero.Application;using RutaCero.Application.Notifications;using RutaCero.Application.Obligations;using RutaCero.Domain.Notifications;using RutaCero.Domain.Obligations;using RutaCero.Domain.ValueObjects;
namespace RutaCero.Application.Tests;
public sealed class NotificationServiceTests
{
 [Fact]public async Task Does_not_generate_duplicate_notification(){var user=Guid.NewGuid();var due=DateOnly.FromDateTime(DateTime.UtcNow);var obligations=new Obligations([new(user,null,ObligationType.Other,"Pago",Currency.HNL,100,null,due,false,DateTimeOffset.UtcNow)]);var notices=new Notices();var service=new NotificationService(notices,obligations,new Unit());await service.GenerateAsync(user,CancellationToken.None);await service.GenerateAsync(user,CancellationToken.None);Assert.Single(notices.Items);}
 private sealed class Notices:INotificationRepository{public List<Notification> Items{get;}=[];public Task<IReadOnlyList<Notification>> ListAsync(Guid u,CancellationToken t)=>Task.FromResult<IReadOnlyList<Notification>>(Items);public Task<bool> ExistsAsync(string k,CancellationToken t)=>Task.FromResult(Items.Any(x=>x.DeduplicationKey==k));public Task<Notification?> FindAsync(Guid id,Guid u,CancellationToken t)=>Task.FromResult(Items.SingleOrDefault(x=>x.Id==id&&x.UserId==u));public Task AddAsync(Notification x,CancellationToken t){Items.Add(x);return Task.CompletedTask;}}
 private sealed class Obligations(IReadOnlyList<PaymentObligation> items):IObligationRepository{public Task<IReadOnlyList<PaymentObligation>> ListAsync(Guid u,DateOnly? f,DateOnly? to,CancellationToken t)=>Task.FromResult(items);public Task<PaymentObligation?> FindAsync(Guid id,Guid u,CancellationToken t)=>Task.FromResult<PaymentObligation?>(null);public Task AddAsync(PaymentObligation x,CancellationToken t)=>Task.CompletedTask;public Task<IReadOnlySet<ObligationScheduleKey>> ListScheduleKeysAsync(Guid u,IReadOnlyCollection<Guid> debtIds,DateOnly from,DateOnly to,CancellationToken t)=>Task.FromResult<IReadOnlySet<ObligationScheduleKey>>(new HashSet<ObligationScheduleKey>());}
 private sealed class Unit:IUnitOfWork{public Task<int> SaveChangesAsync(CancellationToken t)=>Task.FromResult(1);}
}
