using Microsoft.EntityFrameworkCore;
using RutaCero.Domain.Planning;
using RutaCero.Domain.ValueObjects;
namespace RutaCero.Infrastructure.Persistence;
internal static class PlanningConfiguration
{
 public static void Configure(ModelBuilder b){Income(b);Commitment(b);Budget(b);Settings(b);}
 private static void Income(ModelBuilder b){var x=b.Entity<ExpectedIncome>();x.ToTable("expected_incomes");x.HasKey(v=>v.Id);x.Property(v=>v.Id).HasColumnName("id");x.Property(v=>v.UserId).HasColumnName("user_id");x.Property(v=>v.Name).HasColumnName("name");x.Ignore(v=>v.Amount);x.Property<decimal>("_amount").HasColumnName("amount").HasPrecision(18,2);x.Property<Currency>("_currency").HasColumnName("currency").HasConversion<string>();x.Property(v=>v.ExpectedDate).HasColumnName("expected_date");x.Property(v=>v.Frequency).HasColumnName("frequency").HasConversion<string>();x.Property(v=>v.IsConfirmed).HasColumnName("is_confirmed");x.Property(v=>v.DestinationFinancialAccountId).HasColumnName("destination_financial_account_id");x.HasIndex(v=>new{v.UserId,v.ExpectedDate});}
 private static void Commitment(ModelBuilder b){var x=b.Entity<RecurringCommitment>();x.ToTable("recurring_commitments");x.HasKey(v=>v.Id);x.Property(v=>v.Id).HasColumnName("id");x.Property(v=>v.UserId).HasColumnName("user_id");x.Property(v=>v.Name).HasColumnName("name");x.Property(v=>v.CategoryId).HasColumnName("category_id");x.Ignore(v=>v.Amount);x.Property<decimal>("_amount").HasColumnName("amount").HasPrecision(18,2);x.Property<Currency>("_currency").HasColumnName("currency").HasConversion<string>();x.Property(v=>v.Frequency).HasColumnName("frequency").HasConversion<string>();x.Property(v=>v.NextDueDate).HasColumnName("next_due_date");x.Property(v=>v.EndDate).HasColumnName("end_date");x.Property(v=>v.IsEssential).HasColumnName("is_essential");x.Property(v=>v.IsActive).HasColumnName("is_active");x.Property(v=>v.SourceFinancialAccountId).HasColumnName("source_financial_account_id");x.Property(v=>v.DebtId).HasColumnName("debt_id");x.HasIndex(v=>new{v.UserId,v.NextDueDate});}
 private static void Budget(ModelBuilder b){var x=b.Entity<MonthlyBudget>();x.ToTable("monthly_budgets");x.HasKey(v=>v.Id);x.Property(v=>v.Id).HasColumnName("id");x.Property(v=>v.UserId).HasColumnName("user_id");x.Property(v=>v.CategoryId).HasColumnName("category_id");x.Property(v=>v.Year).HasColumnName("year");x.Property(v=>v.Month).HasColumnName("month");x.Ignore(v=>v.Amount);x.Property<decimal>("_amount").HasColumnName("amount").HasPrecision(18,2);x.Property<Currency>("_currency").HasColumnName("currency").HasConversion<string>();x.HasIndex(v=>new{v.UserId,v.CategoryId,v.Year,v.Month}).IsUnique();}
 private static void Settings(ModelBuilder b){var x=b.Entity<UserFinancialSettings>();x.ToTable("user_financial_settings");x.HasKey(v=>v.UserId);x.Property(v=>v.UserId).HasColumnName("user_id");x.Property(v=>v.SafetyReserveAmount).HasColumnName("safety_reserve_amount").HasPrecision(18,2);x.Property(v=>v.SafetyReserveMode).HasColumnName("safety_reserve_mode").HasConversion<string>();x.Property(v=>v.MinimumDaysOfEssentialExpenses).HasColumnName("minimum_days_of_essential_expenses");x.Property(v=>v.DefaultRecommendationProfile).HasColumnName("default_recommendation_profile").HasConversion<string>();x.Property(v=>v.DefaultTimeZone).HasColumnName("default_time_zone");x.Property(v=>v.BaseCurrency).HasColumnName("base_currency").HasConversion<string>();x.Property(v=>v.AllowEstimatedBalancesInRecommendations).HasColumnName("allow_estimated_balances_in_recommendations");}
}
